### ISSUE TITLE
Passive Mode

### ISSUE THREAD

**Issue by chopmann** [bertvv/ansible-role-vsftpd#1]
We use vsftp in Passive Mode, would you accept a pull request with Roles Variables for it or should we just use 'vsftpd_options'?

**Comment by bertvv** [comment]
Yes, PRs are most welcome!
Thanks for your interest!

Cheers,
bert

On 10 March 2016 at 12:09, Cornelio Hopmann notifications@github.com
wrote:

> We use vsftp in Passive Mode, would you accept a pull request with Roles
> Variables for it or should we just use 'vsftpd_options'?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bertvv/ansible-role-vsftpd/issues/1.

## 

Bert Van Vreckem
Lector Informatica

## @bertvanvreckem http://twitter.com/bertvanvreckem

Hogeschool Gent
Faculteit Bedrijf en Organisatie
Valentin Vaerwyckweg 1
9000 Gent
T + 32 9 243 87 87

fbo.hogent.be

**Comment by chopmann** [comment]
I used the vsftp_options. Was the cleanest way to do, i guess.
