### ISSUE TITLE
SELinux boolean ftp_home_dir does not exist on RHEL7.3

### ISSUE THREAD

**Issue by kisamoto** [bertvv/ansible-role-vsftpd#3]
```
$ cat /proc/version
Linux version 3.10.0-327.36.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Mon Oct 24 16:09:20 UTC 2016
$ sudo semanage boolean -l | grep -i ftp_home_dir
tftp_home_dir                  (off  ,  off)  Allow tftp to read and write files in the user home directories
```

Under RHEL7 it appears the SELinux boolean `ftp_home_dir` does not exist which causes the playbook to fail:

```
TASK [bertvv.vsftpd : Set SELinux booleans] ************************************
failed: [localhost] (item=ftp_home_dir) => {"failed": true, "item": "ftp_home_dir", "msg": "SELinux boolean ftp_home_dir does not exist."}
changed: [localhost] => (item=ftpd_full_access)
``` 
Maybe the check is not needed?

**Comment by bertvv** [comment]
That's weird, I have a CentOS 7.2 box that *does* have this SELinux boolean:

```
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
$ cat /proc/version 
Linux version 3.10.0-327.36.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Mon Oct 24 16:09:20 UTC 2016
$ getsebool -a | grep ftp_home
ftp_home_dir --> off
tftp_home_dir --> off
```

**Comment by kisamoto** [comment]
Yes it appears that the boolean is present on CentOS 7 but not RHEL 7

**Comment by bertvv** [comment]
Okay, apparently they removed it in RHEL 7.3 and changed the default to "on". See <https://access.redhat.com/solutions/2857381>. However in 7.2 and earlier, it would still be present. I'll think about this. I don't think many users would be affected if I dropped this.

Thanks for reporting this!

See also <https://bugzilla.redhat.com/show_bug.cgi?id=1352257>

**Comment by kisamoto** [comment]
Excellent spot! That's what I get for using "cutting edge".

My personal recommendation would be able to differentiate between the two;
something like:

```
when: ansible_distribution == "Red Hat Enterprise Linux" and
ansible_distribution_version == "7.3"
```

For now I forked the role and have fixed it locally just by removing it but
this may make it a little more version/future proof.
