### ISSUE TITLE
{{ ansible_selinux }} is defined throws error

### ISSUE THREAD

**Issue by ThomasDetemmerman** [bertvv/ansible-role-vsftpd#4]
**Situation**
This line of code is executed on a Debian/Jessie. Note: no selinux is installed
```
when: ansible_selinux is defined
```

**problem**
When this is executed, the following error is produced:
```
fatal: [192.168.70.2]: FAILED! => {"changed": false, "failed": true, "msg": "libselinux-python required for this module"}
```

**my work-arround**
```
  - name: check if selinux is installed
    command: getenforce
    register: getenfore_result
    ignore_errors: true
```
```
when: getenfore_result.changed == true and ansible_selinux.status == 'enabled'
```

**Comment by bertvv** [comment]
I could not reproduce this error. See the logs of a test run on Travis CI: <https://travis-ci.org/bertvv/ansible-role-vsftpd/jobs/216918514>

Can you check whether you have version 2.0.1 running (see the CHANGELOG.md)? That version should fix this problem (see commit 1fdb6d1b).

I noticed that after releasing v2.0.1, I forgot to import it on Ansible Galaxy. So, maybe you're running an older version.

If you *are* running v2.0.1, we'll have to figure out what's different...

**Comment by ThomasDetemmerman** [comment]
I forked the repo and did the test myself. I managed to reproduce the error without changing anyting.
https://travis-ci.org/ThomasDetemmerman/ansible-role-vsftpd/jobs/216945840

Just one remark: at the time of creating this issue, I was using `when: ansible_selinux is defined`, I noticed that the error is slightly diffrent when using   `when: ansible_selinux is defined and ansible_selinux.status == 'enabled'`. But also this error refers to the same problem. It says that the attribute 'status' does not exists. (because of the fact that ansible_selinux cannot be executed)

I can also confirm I'm using version 2.0.1.

**Comment by bertvv** [comment]
Ooh, that's interesting!

I noticed that the variable `ansible_selinux` can be a boolean or a hash.

On Debian:

```JSON
        "ansible_selinux": false, 
```

on CentOS

```JSON
        "ansible_selinux": {
            "status": "disabled"
        }, 
```

The playbook assumes a hash. Will investigate further.

**Comment by ThomasDetemmerman** [comment]
I think ansible_selinux returns false when it is not properly installed. It's not really related to the OS. I think this issue might be related: https://github.com/ansible/ansible/issues/16612.
```
 if not HAVE_SELINUX:
            self.facts['selinux'] = False
            return
```

**Comment by bertvv** [comment]
I pushed a possible solution, can you try? Take the latest code from github, I haven't released a new version on Ansible yet.

Travis build log: <https://travis-ci.org/bertvv/ansible-role-vsftpd/jobs/217200275>

**Comment by ThomasDetemmerman** [comment]
Yes it works! 

Just to make clear we're on the same page: The situation now is that selinux will be skipped when: (a) It not enabled or (b) Ansible is unable to indentify the status of selinux.

**Comment by bertvv** [comment]
Yes, indeed. Good to know it's fixed, I'll release a new version shortly.
